// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeckWorkShopAPIApp;

#nullable disable

namespace TechWorkShopApp.Migrations
{
    [DbContext(typeof(TechWorkDbContext))]
    [Migration("20250128111350_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TeckWorkShopAPIApp.model.TechWorkShop", b =>
                {
                    b.Property<int>("workShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("trainerId")
                        .HasColumnType("int");

                    b.Property<string>("workShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("workShopId");

                    b.ToTable("TechWorkShop");
                });
#pragma warning restore 612, 618
        }
    }
}
