// <auto-generated />
using System;
using MEtAirwaysCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEtAirwaysCodeFirst.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    partial class FlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MEtAirwaysCodeFirst.Models.MetClass", b =>
                {
                    b.Property<int>("FlightsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlightName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlightType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NoOfSeatsBooked")
                        .HasColumnType("int");

                    b.HasKey("FlightsID");

                    b.ToTable("metclasses");
                });
#pragma warning restore 612, 618
        }
    }
}
